[2025-02-28T05:49:32.769+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_etl_dag.load_to_postgres_file scheduled__2025-02-28T05:35:00+00:00 [queued]>
[2025-02-28T05:49:32.779+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_etl_dag.load_to_postgres_file scheduled__2025-02-28T05:35:00+00:00 [queued]>
[2025-02-28T05:49:32.779+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-02-28T05:49:32.795+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_to_postgres_file> on 2025-02-28 05:35:00+00:00
[2025-02-28T05:49:32.803+0000] {standard_task_runner.py:60} INFO - Started process 2819 to run task
[2025-02-28T05:49:32.807+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_etl_dag', 'load_to_postgres_file', 'scheduled__2025-02-28T05:35:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmp5tim_iqh']
[2025-02-28T05:49:32.810+0000] {standard_task_runner.py:88} INFO - Job 63: Subtask load_to_postgres_file
[2025-02-28T05:49:32.866+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_etl_dag.load_to_postgres_file scheduled__2025-02-28T05:35:00+00:00 [running]> on host 335ace54b661
[2025-02-28T05:49:32.959+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_etl_dag' AIRFLOW_CTX_TASK_ID='load_to_postgres_file' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T05:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-28T05:35:00+00:00'
[2025-02-28T05:49:32.961+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-28T05:49:32.963+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/load_to_postgres.py']
[2025-02-28T05:49:32.979+0000] {subprocess.py:86} INFO - Output:
[2025-02-28T05:49:34.123+0000] {subprocess.py:93} INFO - [INFO] Đã tải file '2025/02/28/12-49-29.csv' từ MinIO
[2025-02-28T05:49:34.124+0000] {subprocess.py:93} INFO - [INFO] Đã nạp 10 bản ghi vào Data Warehouse thành công.
[2025-02-28T05:49:34.124+0000] {subprocess.py:93} INFO - [INFO] Đã tải file '2025/02/28/12-49-30.csv' từ MinIO
[2025-02-28T05:49:34.125+0000] {subprocess.py:93} INFO - [INFO] Đã nạp 10 bản ghi vào Data Warehouse thành công.
[2025-02-28T05:49:34.126+0000] {subprocess.py:93} INFO - [INFO] Quá trình ETL hoàn tất. Đã xử lý 2 file mới từ MinIO.
[2025-02-28T05:49:34.218+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-02-28T05:49:34.244+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=crypto_etl_dag, task_id=load_to_postgres_file, execution_date=20250228T053500, start_date=20250228T054932, end_date=20250228T054934
[2025-02-28T05:49:34.264+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-28T05:49:34.285+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
