[2025-03-01T04:15:06.014+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_etl_dag.load_to_postgres_file scheduled__2025-03-01T04:12:00+00:00 [queued]>
[2025-03-01T04:15:06.024+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_etl_dag.load_to_postgres_file scheduled__2025-03-01T04:12:00+00:00 [queued]>
[2025-03-01T04:15:06.025+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-01T04:15:06.042+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_to_postgres_file> on 2025-03-01 04:12:00+00:00
[2025-03-01T04:15:06.049+0000] {standard_task_runner.py:60} INFO - Started process 902 to run task
[2025-03-01T04:15:06.053+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_etl_dag', 'load_to_postgres_file', 'scheduled__2025-03-01T04:12:00+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpu18pr14s']
[2025-03-01T04:15:06.057+0000] {standard_task_runner.py:88} INFO - Job 277: Subtask load_to_postgres_file
[2025-03-01T04:15:06.117+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_etl_dag.load_to_postgres_file scheduled__2025-03-01T04:12:00+00:00 [running]> on host 335ace54b661
[2025-03-01T04:15:06.209+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_etl_dag' AIRFLOW_CTX_TASK_ID='load_to_postgres_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T04:12:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-01T04:12:00+00:00'
[2025-03-01T04:15:06.213+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-01T04:15:06.214+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/load_to_postgres.py']
[2025-03-01T04:15:06.227+0000] {subprocess.py:86} INFO - Output:
[2025-03-01T04:15:07.536+0000] {subprocess.py:93} INFO - [INFO] Đã tải file '2025/03/01/11-15-03.csv' từ MinIO
[2025-03-01T04:15:07.537+0000] {subprocess.py:93} INFO - [INFO] Đã nạp 10 bản ghi vào Data Warehouse thành công.
[2025-03-01T04:15:07.538+0000] {subprocess.py:93} INFO - [INFO] Quá trình ETL hoàn tất. Đã xử lý 1 file mới từ MinIO.
[2025-03-01T04:15:07.618+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-01T04:15:07.648+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=crypto_etl_dag, task_id=load_to_postgres_file, execution_date=20250301T041200, start_date=20250301T041506, end_date=20250301T041507
[2025-03-01T04:15:07.674+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-01T04:15:07.696+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
